# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XDSFb29heeWjF677BALjyv6l7q-8Ig1m
"""

import json
from urllib.request import urlopen, urlretrieve
import re
import time

with urlopen ('https://data.gov.ua/api/3/action/package_show?id=959dca0a-9b74-41ff-a7c8-f8de6398a219') as response:
  source = response.read()

data = json.loads(source)

#print(json.dumps(data, indent=2, sort_keys=False))
#print(data['result']['resources'])

url_list = list()
for item in data['result']['resources']:
  url_list.append(item['url'])

#print(url_list)

for url in url_list:
  with urlopen (url) as response:
    r = response.read()
  f_name = re.findall('download/([\w\-\.]+)', url)[0]
  print(f_name)
  urlretrieve(url, f_name)
  time.sleep(1)
